### ISSUE TITLE
Use a CDN and move UA file into repo

### ISSUE THREAD

**Issue by ghost** [fijimunkii/real-user-agent#7]
The `ua.json` file can live in this repo and be retrieved with jsDelivr.

Example: https://cdn.jsdelivr.net/gh/fijimunkii/real-user-agent@master/index.js
Browse files: https://cdn.jsdelivr.net/gh/fijimunkii/real-user-agent@master/

How jsDelivr works: https://www.jsdelivr.com/network/infographic
Background: https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/

Docs:
https://www.jsdelivr.com/?docs=gh
https://www.jsdelivr.com/features#gh

**Comment by fijimunkii** [comment]
Great recommendation, thank you @pro-src
