### ISSUE TITLE
Fetch, test, then sync

### ISSUE THREAD

**Issue by ghost** [fijimunkii/real-user-agent#8]
This would prevent bad revisions such as: https://gist.github.com/fijimunkii/952acac988f2d25bef7e0284bc63c406/354c8339ac7c0507d8bc7b451bf0584c719c9d37

Ideally, the CI build would fail and notify you that something went wrong.

**Comment by fijimunkii** [comment]
Thanks for this report @pro-src. The [sync](https://github.com/fijimunkii/real-user-agent/blob/master/sync.js) module does in fact fetch, test, then sync. That bad revision was from initial tests using gist as a host. Cheers

**Comment by ghost** [comment]
Ah, thanks for letting me know. I had assumed that the CI build was responsible for uploading the new `ua.json` via [sync](https://github.com/fijimunkii/real-user-agent/blob/master/sync.js) and didn't see where it was being tested.

Keep up the great work!
